version: '3.8'

services:
  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9002:9002"
    volumes:
      - "D:/workspace/Minio/Groovie:/data"
    command: server /data --console-address ":9002"