spring:
  application:
    name: Groovie
  datasource:
    url: jdbc:postgresql://${POSTGRESQL_HOST:localhost}:${POSTGRESQL_PORT:5432}/${POSTGRESQL_DB:GroovieBackend}
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRESQL_PASSWORD:changeme}
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
  data:
    aws:
      s3:
        access-key: ${AWS_S3_ACCESS_KEY:TWvEKFWytWUUAYab9FyE}
        private-key: ${AWS_S3_PRIVATE_KEY:V0UmtTfvxn9W5EhS1QXA5GZrBJT4LVlQRnFmEn3q}
        region: ${AWS_S3_REGION:ap-southeast-3}
        expiry: ${AWS_S3_EXPIRY:5}
        endpoint: ${AWS_S3_ENDPOINT:http://localhost:9000}
        song-bucket: ${AWS_S3_SONG_BUCKET:song}
  security:
    user:
      name: ${ADMIN_NAME:Hieu}
      password: ${ADMIN_PASSWORD:210503}