spring:
  application:
    name: Groovie
  datasource:
    url: jdbc:postgresql://${POSTGRESQL_HOST:localhost}:${POSTGRESQL_PORT:5432}/${POSTGRESQL_DB:GroovieBackend}
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRESQL_PASSWORD:changeme}
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
  data:
    aws:
      s3:
        access-key: ${AWS_S3_ACCESS_KEY:TWvEKFWytWUUAYab9FyE}
        private-key: ${AWS_S3_PRIVATE_KEY:V0UmtTfvxn9W5EhS1QXA5GZrBJT4LVlQRnFmEn3q}
        region: ${AWS_S3_REGION:ap-southeast-3}
        expiry: ${AWS_S3_EXPIRY:5}
        endpoint: ${AWS_S3_ENDPOINT:http://localhost:9000}
        song-bucket: ${AWS_S3_SONG_BUCKET:song}
        album-bucket: ${AWS_S3_ALBUM_BUCKET:album}
        user-bucket: ${AWS_S3_USER_BUCKET:user}
        route:
          song-audio-route: ${AWS_S3_SONG_AUDIO_ROUTE:audio}
          album-cover-route: ${AWS_S3_ALBUM_COVER_ROUTE:cover}
          user-cover-route: ${AWS_S3_USER_COVER_ROUTE:cover}
  security:
    user:
      name: ${ADMIN_NAME:Hieu}
      password: ${ADMIN_PASSWORD:210503}
  main:
    allow-circular-references: true
  stripe:
    api-secret-key: sk_test_51RI1KjBV063LVQnenAQKpkxycYZc8KMBlnBYWHrqpPv9Gwwo49eyxq1M1D8l3xPlYh92gKj18tqmwi5pbG1agqDm00zRXNW8xX
    webhook-endpoint-secret: whsec_59a6cddd1917e12ab37e9b8004c01cc5a30ebd0a4cf9404da6c114d1cba15041
    artist-subscription-price-id: price_1RKAz1BV063LVQneQyCyxYVK